### ISSUE TITLE
RepNano using Guppy basecalled reads

### ISSUE THREAD

**Issue by vmurigneu** [organic-chemistry/RepNano#2]
Hello,

I read in your paper that you have used reads basecalled by Albacore and Metrichor. Have you tried the RepNano pipeline using reads basecalled by Guppy ?

We are getting an error when trying to preprocess our reads basecalled by Guppy and the corresponding fast5 files:
(tomboenv) python ${repnano}/src/repnano/data/preprocess.py  --hdf5 ${fast5_file} --fastq ${fastq_file} --ref ${ref}  --output_name ${output_fast5} --njobs ${threads}
Total number of reads 4000
Reading reads.fastq
create virtuals by batch of 400
Process by chunk  of 20
0it [00:00, ?it/s]
.................
Total errors 4000
detail of errors:
{'seq_not_found': 4000}
Sucefully processed 0

I also tried to reannotate the fast5 with the fastq using the guidelines under  "Usage (Older files : one fast5 file per read, before 2019)" but it also failed. 
(tomboenv) tombo preprocess annotate_raw_with_fastqs --fast5-basedir ${fast5_directory} --fastq-filenames ${fastq_file} --overwrite --processes 4
[15:28:12] Preparing reads and extracting read identifiers.
****** WARNING ****** Basecalls exsit in specified slot for some reads. Set --overwrite option to overwrite these basecalls.                                                                                                                                          
100%|\| 394/394 [00:08<00:00, 46.19it/s]
[15:28:21] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
[15:29:13] Added sequences to a total of 0 reads.

Thank you for your help,
Valentine

**Comment by hennion** [comment]
Dear Valentine 
We used RepNano with Guppy basecalled fast5 with no problem. Does it happen to all your files? This can happen when the path to the fastq is wrong or when the fastq is corrupted. It might also be possible that depending on the parameters used during the basecaller the read identifier are differents in the fastq and the fast5. I wouldn't recommend to use the older process (it's time and space consuming, it modifies the fast5 file) but if you really want to use it on recent files, you have to add `--bigf` option. 
If you don't manage, we'll see how you could send us test files so that we could try to debug.

**Comment by vmurigneu** [comment]
Thank you for your email
We checked the path to the fastq and the fastq is not corrupted. The fastq is not compressed. The guppy basecaller has been used with default parameters. I tried with two completely different datasets and got the same issue.

**Comment by hennion** [comment]
Thank you for your answer. Could you send us the head of a fastq file so that we can check which ID your basecaller outputs?

**Comment by vmurigneu** [comment]
The headers of fastq files look like that:
@c1c810d1-eb7a-452c-862b-068d655fe7bf runid=0db2e788d272544209f80d04c9f4a1610e27bf94 sampleid=20191009_Rapid read=98867 ch=233 start_time=2019-10-09T05:19:23Z

@cc79d7a6-5a9a-4f20-94de-7c7756177f9b runid=0db2e788d272544209f80d04c9f4a1610e27bf94 sampleid=20191009_Rapid read=108799 ch=67 start_time=2019-10-09T05:19:06Z

**Comment by hennion** [comment]
Thank you, we have to modify our preprocessing to include this format which is not the one we have in our fastq. I'll let you know when it's done.

**Comment by organic-chemistry** [comment]
Hello.
I just updated the code to include this type of header.
I created a test file as we don't have this type of output format.
If it does not work could you provide a link with a fastq and a fast5 ?
Best.

**Comment by vmurigneu** [comment]
Thank you, it worked but the preprocessing step did not complete and did not generate any error message in the stderr file. I re ran interactively using another fast5 file and got the following error message, which looks like a tombo error message: 

 Total number of reads 4000
Reading /scratch/90days/raw_data/20200129_Brdu0.fastq
si 4000
create virtuals by batch of 400
Process by chunk  of 20
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [02:36<00:00,  7.83s/it]
create virtuals by batch of 400
Process by chunk  of 20
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [02:55<00:00,  8.78s/it]
create virtuals by batch of 400
Process by chunk  of 20
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [02:21<00:00,  7.08s/it]
******************** ERROR ********************
	Invalid sequence encountered from genome sequence.
******************** ERROR ********************
	Invalid sequence encountered from genome sequence.

Have you already encountered the same error? 

Thanks again for your help

**Comment by organic-chemistry** [comment]
Hi,
I never encountered this error.
To me it looks like there could be non-canonical bases in your fasta that could lead to this error.
Could you check that you only have A,T,C G ?
I could try to catch this error if it only happens for some of the reads.
I think the error message should be more informativ if you run the same code bu with njobs set to one. Could you post the error here?
Best

**Comment by vmurigneu** [comment]
Hi again, 
Yes I thought the same and checked the content of the fasta using seqkit and it did not return any error. There are N in the fasta but it should be fine? I tried again with njobs =1 but the error message remains the same:

(tomboenv) [vmurig@delta004 ref]$ python ${repnano}/src/repnano/data/preprocess.py  --hdf5 ${fast5_file} --fastq ${fastq_file} --ref ${ref}  --output_name ${output_fast5} --njobs 1
Total number of reads 4000
Reading /scratch/90days/TEL/raw_data/20200129_Brdu0.fastq
si 4000
create virtuals by batch of 400
/scratch/90days/TEL/sw/RepNano/src/repnano/data/preprocess.py:281: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(virtual) as h5:
/scratch/90days/TEL/sw/RepNano/src/repnano/data/preprocess.py:276: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  read2.create_dataset("Signal", shape, dtype="<i2", data=raw_source["Signal"].value)
 15%|██████████████████████▌                                                                                                                             | 61/400 [00:26<01:48,  3.11it/s]******************** ERROR ********************
	Invalid sequence encountered from genome sequence.
******************** ERROR ********************
	Invalid sequence encountered from genome sequence.
 15%|██████████████████████▌       

I have tried again using this UCSC reference genome and got the same issue.
https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz

34%|██████████████████████████████████████████████████▎                                                                                                | 137/400 [00:53<01:10,  3.73it/s]******************** ERROR ********************
	Invalid sequence encountered from genome sequence.
******************** ERROR ********************
	Invalid sequence encountered from genome sequence.

With another fast5, the processing was successful for 800 reads and then the same error appeared on the next 400 reads.

**Comment by organic-chemistry** [comment]
The N are not fine.
What do they stand for? Unknown base?
I think that they are the problem, because in our method we compute the expected current from the sequence. And the sequence only allow for ATCG.
I suggest If you can, to remove the N or replace them by any base if they are not too numerous.
If this is standard that there are N in the sequence, we can also try to adress this problem.
What do you think @hennion

**Comment by hennion** [comment]
Indeed when Tombo convert the reference sequence to the expected current values, there should be no 'N' (see piece of code below). To avoid this, either you modify your reference fasta to avoid the Ns (I would suggest to replace them by *A* for instance to keep the coordinates OK), or we could try to filter out reads that map in a region that contains some Ns before doing this conversion.  

```
def get_exp_levels_from_seq(self, seq, rev_strand=False):
        """Compute expected signal levels for a sequence
        Args:
            seq (str): genomic seqeunce to be converted to expected signal
                levels
            rev_strand (bool): provided sequence is from reverse strand (so
                flip return order to genome forward direction)
        Note:
            Returned expected signal levels will be trimmed compared to the
            passed sequence based on the `std_ref.kmer_width` and
            `std_ref.central_pos`.
        Returns:
            Expected signal level references
            1) ref_means (`np.array::np.float64`) expected signal levels
            2) ref_sds (`np.array::np.float64`) expected signal level sds
        """
        seq_kmers = th.get_seq_kmers(seq, self.kmer_width, rev_strand)

        try:
            ref_means = np.array([self.means[kmer] for kmer in seq_kmers])
            ref_sds = np.array([self.sds[kmer] for kmer in seq_kmers])
        except KeyError:
            th.error_message_and_exit(
                'Invalid sequence encountered from genome sequence.')

        return ref_means, ref_sds
```

**Comment by vmurigneu** [comment]
thank you, it worked after replacing the N by A in the fasta file

**Comment by organic-chemistry** [comment]
Great!
