### ISSUE TITLE
Altering parameters for ForkPrediction-CNN-TM.py

### ISSUE THREAD

**Issue by melkramer** [organic-chemistry/RepNano#4]
Hello,

I am working with the Stillman lab at CSHL and we have done some test runs of BrdU labelled yeast samples on PromethION. Using default parameters, we achieve robust mapping rates, but we are detecting only ~5000 forks, and we are getting only a very small number of initiation and termination events detected.  Can you please suggest which parameters to alter to help us increase detection?

Thank you,
Melissa Kramer

**Comment by hennion** [comment]
Dear Ms Kramer, 
just a few questions to understand the problem. 
How many reads to you have in your experiment ?
Do you used asynchronous cells ? 
Do you have a similar number of forks with the 2 methods?
Could you visualize the BrdU signal? If you want you can send me some .fa_ratio_B file so that I could have a look. Maybe the signal has low amplitude and you need to reduce MinJump and maybe also MinAmplitude and Stdev. The risk being to detect noise if you're not stringent enough... 
Best wishes
Magali

**Comment by melkramer** [comment]
Hello Magali,


Thank you so much for your prompt response!  Yes we did use asynchronous cells and did the labeling according to the protocol of the FORKseq paper.  We get almost all of the FORK calls from the CNN rather than the TM method on both runs.


For the first run we had 4,452,000 reads with an N50 readlength of ~11kb (~3200 forks detected by CNN, 21 by TM).


For the second run we had 5,820,861 reads with an N50 readlength of over 37kb (~5300 forks detected by CNN, 30 by TM).


I will work on getting you the ratio files.


Thank you,

Melissa


________________________________

**Comment by melkramer** [comment]
Hi again,


Apologies but can you also confirm the output file column  headers?  I inferred them from the code but want to double check just in case.


Thank you!

Melissa


________________________________

**Comment by hennion** [comment]
Yes sorry for that, I realized that some details are missing. We'll publish a more detailed protocol soon. Don't hesitate to ask your questions in the mean time. 
[header.pdf](https://github.com/organic-chemistry/RepNano/files/6245763/header.pdf)

**Comment by melkramer** [comment]
Hi Magali,


The server rejected the large attachment for the ratio_B file I tried to send.  Is there an ftp site I can use to share files with you?


Thank you,
Melissa


________________________________

**Comment by hennion** [comment]
Dear Melissa, 
sorry for the delay, I don't have a server where you can write, but you can put the files on your institutional server if you have one and send me the link by email : hennion at ens dot fr . Or using an external sharing solution such as wetransfer if the data is not sensitive. If possible, I'd like to see also the TM results as I'm surprised that you have almost no forks.  
Best wishes
Magali

**Comment by melkramer** [comment]
Hi Magali,


I have placed the detected events output files (default parameters and after I lowered jumpscore) as well some of the ratio files on our ftp site (please let me know if you need to see more).  I will send the download info separately to your private email.


One thing we realized is that we used a different strain (see below).  Could this be the reason our signal might be lower?


Here is the strain information that we used:
MATa ade2-1 ura3-1 trp1-1,112 can1-100, his 3-11,15
bar1∆::TRP1
leu2-3::LEU2-BrdU-Inc (cassette includes: ADH1–hENT1 and GPD–HSV–TK)
orc4::TRP1
his3::NTAP-ORC4

Strain information from the original paper:
MATa ade2-1 trp1-1 can1-100 leu2-3 his3-11,15
bar1::LEU2
ura3-1::URA3-GPD-TK7x
aur1::AUR1-C-ADH-hENT1
cdc21::kanMX


Thank you so much for your help!


Best,

Melissa


________________________________

**Comment by hennion** [comment]
Dear Melissa,
I think you're right, the strain you use probably doesn't incorporate enough BrdU to give a clear signal (but I haven't look at your data yet). We used a cdc21 deficient strain to maximize BrdU incorporation.  
Best wishes, 
Magali

**Comment by melkramer** [comment]
Hi Magali,


I was wondering if you had a chance to look at our data?  Also I was wondering if you might be bale to advise me on how we could visualize our raw signal compared to ratio files from your work?  I downloaded the processed calls (forks, initiation, termination events) from your work but I didn't think that level of raw signal data was available, am I mistaken?


Thank you very much for your help,

Melissa



________________________________

**Comment by hennion** [comment]
Dear Melissa, 
I'm very sorry for the delay... You can download a test dataset to see our raw signal at https://www.opendata.bio.ens.psl.eu/FORK-seq/ . I'll send you soon a script to visualize the signal.
Magali

**Comment by melkramer** [comment]
Thank you Magali, that will be very helpful!!


Best,
Melissa


________________________________

**Comment by melkramer** [comment]
Hi Magali,


I have downloaded the test data set, thanks again. If you can send along the script we would truly appreciate it!


Thank you,
Melissa


________________________________

**Comment by hennion** [comment]
Dear Melissa, 
I added a small script ForkPredictionPlot.py in src/repnano/detection/ that you can use on the test data or on your data. 
```
python src/repnano/detection/ForkPredictionPlot.py BrdU_calls/ outputName
```
I'd like to have the .fa files corresponding to the .fa_ratio_B files so that I could have a closer look at your data, and maybe improve the script to help you more. 
Best wishes, 

Magali
